### PR TITLE
Adds support for creating graphs straight from shapefiles on a command line

### PR DESCRIPTION
**Pull request by Isaquedanielre**

### CODE REVIEW

**Comment by pedrocamargo** [comment]
Isaque, this change, among others, will only make into master when they have been tested against a few different networks.  Any reason why you can't work from the dev0.31 branch?

**Comment by Isaquedanielre** [comment]
Hi Pedro, no special motivation, only beacuse I saw the modification, so i thought which is the newest...

**Comment by pedrocamargo** [comment]
Isaque,
             I am keeping that branch under development for a few weeks
until I can finish and test one particular batch of changes, which include
some of the issues I raised for myself on GitHub and a any other fixes
people find necessary.

```
         I will try to keep the development cycles from 3 to 4 weeks,
```

when I will re-upload to the QGIS repository.

Cheers,
Pedro

**Comment by Isaquedanielre** [comment]
So, I can use the master? 
Or wait for your changes?
Best 
Isaque

**Comment by pedrocamargo** [comment]
You can use either one. The only difference is that the dev branch is the
bleeding edge. If you don;t need those features, you can use the master
branch.

Cheers,
Pedro

**Pull request merged**
