### PR TITLE
Qgis 3

### PR DESCRIPTION
**Pull request by pedrocamargo**
It is time to make AequilibraE for QGIS 3 official.

Most of the pull requests that made the QGIS3 branch were properly reviewed, but it is the law that pull requests into master need review!  :-)

### CODE REVIEW

**Comment by arobrien** [comment]
There's no way that this is getting an effective code review.

I propose install and test key functionality. Do you have a list of key features to test, @pedrocamargo?

**Comment by pedrocamargo** [comment]
@arobrien ,   I agree with you.  
I am tempted to just merge it for the following reasons:
- This is a collection of pull requests that, on their own, have all been reviewed already
- The latest (experimental) release based on this branch has 800 downloads and the very few bugs reported have been fixed already

What is your take?

**Comment by ychtw** [comment]
@pedrocamargo , please also feel free to remove those branches start with my name.
Thanks!

**Comment by pedrocamargo** [comment]
@arobrien 

As we talked before, I think we should just merge this branch for the following reasons:

- A version based on this branch has been released on experimental mode a few months ago and has already seen over 750 downloads
- All bugs reported since the release have been fixed (plus older bugs)
- The individual pull requests that created this branch have been individually checked
- I have manually tested each and every tool

**Review by arobrien — APPROVED** [review]

**Pull request merged**
